pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/nanahj/250324a.git'
            }
        }          
        stage('Build') {
            steps {
                dir('./step07_cicd') {                   
                   sh 'chmod +x gradlew'    
	      sh './gradlew build'
                }
            }
        }               
    }
    post {
        success {
            echo '✅ 빌드 성공!'
        }
        failure {
            echo '❌ 빌드 실패! 오류 확인 필요!'
        }
    }
}